services:
  webdav:
    image: bytemark/webdav
    container_name: koreader_webdav
    restart: always
    ports:
      - "${WEBDAV_PORT:-8080}:80"
    environment:
      - USERNAME=${WEBDAV_USERNAME}
      - PASSWORD=${WEBDAV_PASSWORD}
    volumes:
      - ./koreader-data:/var/lib/dav
